baseURL: "https://www.golangroma.it/"
languageCode: "it-it"
title: "Golang Roma"
theme: "PaperMod"
enableEmoji: true
googleAnalytics: G-VJ6WSD4SWZ

params:
  defaultTheme: light
  disableThemeToggle: true

  profileMode:
    enabled: true
    subtitle: "Seguici sui nostri canali"
    imageUrl: "images/golangroma.png" # optional
    imageWidth: 170 # custom size
    imageHeight: 170 # custom size

  socialIcons: # optional
    - name: github
      url: "https://github.com/golangroma"
    - name: twitter
      url: https://twitter.com/golangroma
    - name: telegram
      url: https://t.me/+-2rfddb0IhQzN2Ri
    - name: youtube
      url: https://youtube.com/channel/UCiMlT250vckF5KT53Z5xVUQ
    - name: meetup
      url: https://meetup.com/golangroma
